### PR TITLE
Add TS typings

### LINKED ISSUE #8: TypeScript definitions
Hi,

Trying `nano-memoize`, I realized there isn't any TypeScript definitions whereas some of the compared modules has.

Below is TypeScript definitions for `nano-memoize`. You may want to optimize `serializer` and `equals`, but currently it seems to work fine.

```ts
declare module "nano-memoize" {
  export default function memoized<T extends Function>(
    func: T,
    options?: {
      /**
       * Only use the provided maxArgs for cache look-up, useful for ignoring final callback arguments
       */
      maxArgs?: number;
      /**
       * Number of milliseconds to cache a result, set to `Infinity` to never create timers or expire
       */
      maxAge?: number;
      /**
       * The serializer/key generator to use for single argument functions (optional, not recommended)
       * must be able to serialize objects and functions, by default a WeakMap is used internally without serializing
       */
      serializer?: (...args: any[]) => any;
      /**
       * the equals function to use for multi-argument functions (optional, try to avoid) e.g. deepEquals for objects
       */
      equals?: (...args: any[]) => boolean;
      /**
       * Forces the use of multi-argument paradigm, auto set if function has a spread argument or uses `arguments` in its body.
       */
      vargs?: boolean;
    }
  ): T;
}
```

### PR DESCRIPTION
**Pull request by markogresak**
Closes #8
Credits for typings to @ozum and @ercmage

Co-Authored-By: Özüm Eldoğan <1497060+ozum@users.noreply.github.com>
Co-Authored-By: 0xErcMage <83504078+ercmage@users.noreply.github.com>

### CODE REVIEW

**Comment by markogresak** [comment]
@anywhichway I have tested this with `npm link` and I can confirm the typings are working as expected.

I would appreciate if this PR was merged and deployed to make `nano-memoize` work with typescript out of the box.

**Comment by MohamedLamineAllal** [comment]
Absolutely! Typescript typing are a must no a days! I work only with typescript. A package that miss that is so tickling

**Comment by ciriousjoker** [comment]
Can someone please merge this?

**Comment by anywhichway** [comment]
Unfortunately, I do not know TS and am reluctant to merge something I do not understand.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ciriousjoker** [comment]
@anywhichway The commit doesn't change any functionality. It just declares typings (.d.ts file) and "registers" it in the package.json, so they are considered when suggesting autocompletions.

The typings match your documentation except that callTimeout is missing. If you just insert this after line 11:

```ts
  /*
   * Go ahead and call memoized multi-args functions after a number of milliseconds via a timeout after the 
   * cached result has been returned, perhaps to ensure that callbacks are invoked, does not cache the timemout result
   * e.g. `nanomemoize(function(a,b,cb) { var result = a + b; cb(result); return result; },{maxArgs:2,callTimeout:0});`
   */
  callTimeout: number,
```

you can safely merge this without breaking existing code. If you don't, existing code that uses the callTimeout will throw a compile error that callTimeout isn't a known property.

If you don't want to do that fine, I guess unmaintained libraries are bound to die eventually anyway.

**Pull request merged**
