### PR TITLE
move package to es modules

### PR DESCRIPTION
**Pull request by 43081j**
in case you ever want it:

* removed all the uglify/browserify/etc clutter
* rewrote the sources, tests and benchmarks to use es modules
* removed object.assign (used object spread instead)

on a side note, there's little use having your sources in an unreadable/minified state. you should write it cleanly and readable then use tooling (terser) to minify it IMHO. your distributed code can still be small but your sources actually readable in that case. 

theoretically this means it'd work in a browser too using an `import`.

it'd be a breaking change, cjs wouldn't be supported anymore. a major version bump would be appropriate

### CODE REVIEW

**Comment by anywhichway** [comment]
Hi James,

1) Not sure what browserify and uglify are if not tooling (granted a little dated) applied to /index.js.
2) I have lost count of the number of times I have forked packages and the author's tooling simply did not work; hence, the inclusion of /dist and /browser directories.
3) I tried more "mature" build piplelines/tools and modules last year (13 months agao) and simply could not get the best transpiled size and performance across server and browser implementations.
4) I have always ensured that code intended to run in the browser or on the server can be tested on both. Once again, bitten too many times.

Have you re-run the benchmarks and checked the transpiled size for your modifications?

All the above being said, I had a bit of a Forest Gump moment Dec 23rd of last year. I simply stopped coding. Even when I was an SVP or CTO I would code a few hours a day as a hobby. Nano-memozie was one of my hobby projects. Then in April of this year I pretty much retired.

I am happy to transfer the GitHub repo and  NPM package to you if you wish.

I will not be merging your request, not because I don't appreciate the work, just because I do not code anymore and it is too risky.

Best Regards,

Simon

**Comment by 43081j** [comment]
1. They were doing that job, i'm not disagreeing with that. `src/nano-memoize.js` is written as if it too is minified (presumably to save some bytes) when it really doesn't need to be. the sources could be clean, readable code and the distributed JS could be minified at build time
2. these days it should really be the responsibility of the consumer to do any bundling IMO. you can simplify your repo massively by shipping a native browser module (ESM) and leave it up to the consumer to deal with compatibility etc (by bundling or whatever else)
3. node and browsers all support ESM now, this should work as-is out of the box. the logic hasn't changed other than dropping Object.assign (which isn't necessary to move to ESM), so it should perform just the same. if it doesn't your 'benchmark' must be taking into account module loading performance which isn't your concern, but is rather measure of the platform's performance
4. it can be. i removed the index.html because nothing referenced it (presumably you ran it manually). we could very easily run it in chrome automatically for example

anyway its no worries if you don't have the time/interest anymore in this.

i don't have a huge amount of free time but i'd be happy to take over it if thats what you'd prefer. though i'd probably move to a structure like this and keep it an esm-only repo. so if you'd rather it be left alone, thats fine we can discard this PR :)

thanks a lot for taking the time to respond

**Comment by anywhichway** [comment]
Hi James, started coding again last month. I will take a look at merging your changes. Nothing I fundamentally disagree with in your comments.

**Comment by anywhichway** [comment]
Hi James, I completed this work while making other improvements.

**Pull request closed without merging**
