### PR TITLE
fix README.md

### PR DESCRIPTION
**Pull request by crapthings**

### CODE REVIEW

**Comment by crapthings** [comment]
its just the wrong typing

-nmp install nano-memoize

**Comment by caiogondim** [comment]
@anywhichway Indeed. The nano-memoize being fastest is not true anymore. You can update the README.

**Comment by caiogondim** [comment]
An of course, thanks for the amazing PR.

**Comment by anywhichway** [comment]
I did update and re-benchmark using your version from a few hours ago after you merged the pull.

On my machine nano has a marginal but un-important edge. What are you testing on?

**Pull request merged**
