### PR TITLE
Make callTimeout optional in the typings as it isn't yet used in the JS side

### PR DESCRIPTION
**Pull request by SirHall**

### CODE REVIEW

**Comment by anywhichway** [comment]
@SirHall Thanks for the pull request. A favor please ... I am not a TypeScript person (I understand how a lot of people get value out if it, but I have not personally found much benefit). As a result, the fact that there is a `callTimeout` option even in the TypeScript defs is a side effect of a pull I accepted without really understanding it. Since `callTimeout` is not used in the JavaScript and since I have not seen a good case for simply waiting because one thinks there may be callbacks, I think `callTimeout` should simply be dropped. Could you make that change and re-submit a pull?

**Comment by SirHall** [comment]
Not to worry, my assumption was simply that there was some in-progress work that would be using it and didn't want to tread on other work, there is also the concern that technically since this will cause code that uses it to fail compilation that it will require a new major version.

Would this be a good enough reason to jump to `v2.0.0`, or do you have some other idea?

**Comment by anywhichway** [comment]
I am fine going to 2.0 if you make the change. I Will then update the readme.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SirHall** [comment]
I believe this should be ready to merge, the version has been increased to v2.0.0 in `package.json`.

**Comment by anywhichway** [comment]
@SirHall I have merged and pulled to a local environment. Unfortunately, testing is now broken. I will fix this before publishing the new version to NPM.

**Comment by anywhichway** [comment]
@SirHall it was a very quick fix, new version published to NPM

**Pull request merged**
